packages:
  - 'packages/*'

allowBuilds:
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true

catalog:
  typescript: ^6.0.3
  '@nestjs/common': ^11.1.28
  '@nestjs/swagger': ^11.4.6
  class-validator: ^0.15.1
  class-transformer: ^0.5.1
  typeorm: ^0.3.31
  dayjs: ^1.11.21
  argon2: ^0.45.1
  reflect-metadata: ^0.2.2
  '@types/node': ^25.9.5

  tsdown: ^0.22.14
  turbo: ^2.10.9
  '@biomejs/biome': ^2.5.8
  '@changesets/cli': ^3.0.1
  vitest: ^4.1.10
  '@vitest/coverage-v8': ^4.1.10
  unplugin-swc: ^1.5.10
  '@swc/core': ^1.15.47
  '@arethetypeswrong/cli': ^0.18.5
